# Generated by Django 5.1.2 on 2025-01-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_task_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupuser',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='groupuser',
            name='tasks_solved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('full', 'Full'), ('available', 'Available'), ('finished', 'Finished'), ('failed', 'Failed')], default='available', max_length=15),
        ),
    ]
