# Generated by Django 5.1.2 on 2025-01-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_task_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='join_code',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
